# Generated by Django 4.2.2 on 2023-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("transportation", "Transportation"),
                            ("housing", "Housing"),
                            ("education", "Education"),
                            ("shopping", "Shopping"),
                            ("travel", "Travel"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
