# Generated by Django 4.2.2 on 2023-07-10 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
